FC=gfortran
# Add source folder here
SOURCEDIR=THESOURCE
# Default flags, please adapt
# FLAGS for gfortran
FCFLAGS=-mcmodel=medium -I$(SOURCEDIR)/hostcode/  -I$(SOURCEDIR)/devicecode/

AR=ar
RM=rm
ARFLAGS=cr
RANLIB=ranlib
# set this to 1 if you want to use gfortran
# set both to 1 if you want to use mpifortran
NODEVICE=1
MPARALLEL=0

%.o: %.f90 $(DEPENDALL)
	${FC} -c ${FCFLAGS} $<


